### ISSUE TITLE
Plans for further development?

### ISSUE THREAD

**Issue by saket** [nickhristov/krakdown#3]
Hey @nickhristov, this looks like a great project. Do you have any plans for continuing development on this? 

I'm trying to leverage Kotlin multiplatform for building a cross-platform markdown editor app. Although it's possible to use separate parsers for each platform, using a single parser for all platforms will make things so much simpler.

I found a couple of other similar projects on Github, but your code feels the most readable of them all.

**Comment by thawkins** [comment]
also is it on Maven, so i can just reference it as a dependency on build.gradle.kts file?

**Comment by nickhristov** [comment]
I haven't put much effort into this for about a year. I also have not put this on maven as I did not feel that it was stable enough (and the markdown coverage is not where I want it to be).

I have quite a few things going on at the moment. I may pick this up again in the upcoming summer.

**Comment by saket** [comment]
Understandable, thank you!
